apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::045877548542:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-J5MV7VKHILUM
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-15T02:48:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "926"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4035de7b-4aaf-48a9-bab6-0a28fd6b7fd4
